framework:
    default_locale: en
    translator:
        fallbacks: ['en']
        paths:
            - '%kernel.project_dir%/translations/email'
            - '%kernel.project_dir%/translations/notification'
            - '%kernel.project_dir%/translations/timezone'
            - '%kernel.project_dir%/translations'
