twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%env(APP_NAME)%'
        app_front_url: '%env(APP_FRONT_URL)%'
        api_url: '%env(API_URL)%'
