<?php

namespace App\Repository\Tracker;

use App\Entity\Tracker\TrackerHistoryIOLast;
use App\Entity\Tracker\TrackerIOType;
use Doctrine\ORM\EntityRepository;

/**
 * TrackerHistoryIOLastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerHistoryIOLastRepository extends EntityRepository
{
    /**
     * @param int $deviceId
     * @param TrackerIOType $type
     * @return TrackerHistoryIOLast|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLastRecordByDeviceIdAndType(
        int $deviceId,
        TrackerIOType $type
    ): ?TrackerHistoryIOLast {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('thiol')
            ->from(TrackerHistoryIOLast::class, 'thiol')
            ->where('IDENTITY(thiol.device) = :deviceId')
            ->andWhere('thiol.type = :type')
            ->setParameter('deviceId', $deviceId)
            ->setParameter('type', $type)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    public function getByDeviceId(int $deviceId,): ?array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('thiol')
            ->from(TrackerHistoryIOLast::class, 'thiol')
            ->where('IDENTITY(thiol.device) = :deviceId')
            ->setParameter('deviceId', $deviceId)
            ->getQuery()
            ->getResult();
    }
}
