<?php

namespace App\Repository\Tracker;

use App\Entity\Device;
use App\Entity\Tracker\TraccarEventHistory;

/**
 * TraccarEventHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraccarEventHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Device $device
     * @param $eventTime
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function recordExistsForDevice(Device $device, $eventTime)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('COUNT(teh)')
            ->from(TraccarEventHistory::class, 'teh')
            ->where('teh.occurredAt = :eventTime')
            ->andWhere('teh.device = :device')
            ->setParameter('eventTime', $eventTime)
            ->setParameter('device', $device)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
