<?php

namespace App\Repository\Tracker;

/**
 * TrackerPayloadUnknownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerPayloadUnknownRepository extends \Doctrine\ORM\EntityRepository
{

}
