<?php

namespace App\Repository\Tracker;

use Doctrine\Common\Collections\Criteria;
use App\Entity\Tracker\TrackerAuth;

/**
 * TrackerAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerAuthRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $socketId
     * @return object|TrackerAuth|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneBySocketId($socketId)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ta')
            ->from(TrackerAuth::class, 'ta')
            ->where('ta.socketId = :socketId')
            ->setParameter('socketId', $socketId)
            ->orderBy('ta.createdAt', Criteria::DESC)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * @param $socketId
     * @return |null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findImeiBySocketId($socketId)
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ta.imei')
            ->from(TrackerAuth::class, 'ta')
            ->where('ta.socketId = :socketId')
            ->setParameter('socketId', $socketId)
            ->orderBy('ta.createdAt', Criteria::DESC)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $result ? $result['imei'] : null;
    }

    /**
     * @param string$imei
     * @return object|TrackerAuth|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByImei($imei)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ta')
            ->from(TrackerAuth::class, 'ta')
            ->where('ta.imei = :imei')
            ->setParameter('imei', $imei)
            ->orderBy('ta.createdAt', Criteria::DESC)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
