<?php

namespace App\Repository\Tracker;

use App\Entity\Tracker\TrackerIOType;
use Doctrine\Common\Collections\Criteria;

/**
 * TrackerIOTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerIOTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function getAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('tiot')
            ->from(TrackerIOType::class, 'tiot')
            ->orderBy('tiot.order', Criteria::ASC)
            ->getQuery()
            ->getResult();
    }
}
