<?php

namespace App\Repository;

use App\Entity\Asset;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAssetsWithNewData(string $dateFrom): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from(Asset::class, 'a')
            ->leftJoin('a.lastTrackerHistorySensor', 'lths')
            ->andWhere('lths.occurredAt > :dateFrom')
            ->setParameter('dateFrom', $dateFrom)
            ->getQuery()
            ->getResult();
    }
}
