<?php

namespace App\Repository;

use App\Entity\ChatHistoryUnread;

/**
 * ChatHistoryUnreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatHistoryUnreadRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @return int
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getUserTotalUnreadCount(int $userId): int
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(chu.id)')
            ->from(ChatHistoryUnread::class, 'chu')
            ->where('chu.user = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $userId
     * @return array
     */
    public function getAllByUser(int $userId): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('chu')
            ->from(ChatHistoryUnread::class, 'chu')
            ->where('chu.user = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getResult();
    }
}
