<?php

namespace App\Repository;

use App\Entity\Depot;
use App\Entity\User;
use App\Entity\UserGroup;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVehicleDepotById(User $user, $id)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('vd')
            ->from(Depot::class, 'vd')
            ->andWhere('vd.id = :id')
            ->setParameter('id', $id)
            ->andWhere('vd.team = :team')
            ->setParameter('team', $user->getTeam());

        if ($user->needToCheckUserGroup()) {
            $userVehicleDepots = $this->getEntityManager()->getRepository(UserGroup::class)
                ->getUserDepotsIdFromUserGroup($user);

            $q->andWhere('vd.id in (:vehicleDepotIds)')
                ->setParameter('vehicleDepotIds', $userVehicleDepots);
        }

        return $q->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }
}
