<?php

namespace App\Repository;

use App\Entity\DeviceVendor;

/**
 * DeviceVendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceVendorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $vendor
     * @return DeviceVendor|object|null
     */
    public function findByVendorName($vendor)
    {
        return $this->findOneBy(['name' => $vendor]);
    }

    /**
     * @param $vendor
     * @return int|mixed|string|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findVendor($vendor)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dv')
            ->from(DeviceVendor::class, 'dv')
            ->andWhere('lower(dv.name) = lower(:vendor)')
            ->setParameter('vendor', $vendor)
            ->getQuery()
            ->setMaxResults(1)
            ->useQueryCache(true)
            ->enableResultCache(3600)
            ->getOneOrNullResult();
    }
}
