<?php

namespace App\Repository;

use App\Entity\DeviceModel;
use App\Entity\DeviceVendor;
use Doctrine\ORM\Query\Expr;

/**
 * DeviceModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceModelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param DeviceVendor $vendor
     * @param $model
     * @return int|mixed|string|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getModel(DeviceVendor $vendor, $model)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dm')
            ->from(DeviceModel::class, 'dm')
            ->leftJoin(DeviceVendor::class, 'dv', Expr\Join::WITH, 'dm.vendor = dv')
            ->andWhere('lower(dm.name) = lower(:model)')
            ->andWhere('dv = :vendor')
            ->setParameter('model', $model)
            ->setParameter('vendor', $vendor)
            ->getQuery()
            ->setMaxResults(1)
            ->useQueryCache(true)
            ->enableResultCache(3600)
            ->getOneOrNullResult();
    }
}
