<?php

namespace App\Repository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceCameraEventTypeRepository extends \Doctrine\ORM\EntityRepository
{

}
