<?php

namespace App\Repository;

use App\Entity\DeviceCameraEvent;
use App\Entity\DeviceCameraEventFile;
use App\Entity\Vehicle;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr\Join;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceCameraEventFileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $remoteId
     * @param DeviceCameraEvent $dce
     * @return DeviceCameraEventFile|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByRemoteIdAndEvent(string $remoteId, DeviceCameraEvent $dce): ?DeviceCameraEventFile
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dcef')
            ->from(DeviceCameraEventFile::class, 'dcef')
            ->where('dcef.remoteId = :remoteId')
            ->andWhere('dcef.event = :event')
            ->setParameter('event', $dce)
            ->setParameter('remoteId', $remoteId)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * @param \DateTimeInterface|string $dateFrom
     * @param \DateTimeInterface|string $dateTo
     * @param array $params
     * @param string $sort
     * @param string $order
     * @return Query
     */
    public function getAllByRangeQuery(
        $dateFrom,
        $dateTo,
        array $params,
        string $sort,
        string $order
    ): Query {
        $deviceId = $params['deviceId'] ?? null;
        $deviceIds = $params['deviceIds'] ?? null;
        $vehicleId = $params['vehicleId'] ?? null;
        $vehicleIds = $params['vehicleIds'] ?? null;
        $regNo = $params['regNo'] ?? null;
        $driverId = $params['driverId'] ?? null;
        $teamIds = $params['teamId'] ?? null;
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dcef')
            ->from(DeviceCameraEventFile::class, 'dcef')
            ->leftJoin(DeviceCameraEvent::class, 'dce', Join::WITH, 'dcef.event = dce')
            ->orderBy('dcef.' . $sort, $order);

        if ($dateFrom) {
            $query->andWhere('dcef.startedAt >= :dateFrom')
                ->setParameter('dateFrom', $dateFrom);
        }
        if ($dateTo) {
            $query->andWhere('dcef.startedAt <= :dateTo')
                ->setParameter('dateTo', $dateTo);
        }
        if ($deviceId) {
            $query->andWhere('IDENTITY(dce.device) = :deviceId')
                ->setParameter('deviceId', $deviceId);
        }
        if ($deviceIds) {
            $query->andWhere('IDENTITY(dce.device) IN (:deviceIds)')
                ->setParameter('deviceIds', $deviceIds);
        }
        if ($driverId) {
            $query->andWhere('IDENTITY(dce.driver) = :driverId')
                ->setParameter('driverId', $driverId);
        }
        if ($vehicleId) {
            $query->andWhere('IDENTITY(dce.vehicle) = :vehicleId')
                ->setParameter('vehicleId', $vehicleId);
        }
        if ($vehicleIds) {
            $query->andWhere('IDENTITY(dce.vehicle) IN (:vehicleIds)')
                ->setParameter('vehicleIds', $vehicleIds);
        }
        if ($regNo) {
            $query->leftJoin(Vehicle::class, 'v', Join::WITH, 'dce.vehicle = v')
                ->andWhere('LOWER(v.regNo) LIKE LOWER(:regNo)')
                ->setParameter('regNo', '%' . $regNo . '%');
        }
        if ($teamIds) {
            $query->andWhere('IDENTITY(dce.team) IN (:teamIds)')
                ->setParameter('teamIds', $teamIds);
        }

        return $query->getQuery();
    }
}
