<?php

declare(strict_types = 1);

namespace App\Repository;

/**
 * DigitalFormAnswerStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigitalFormAnswerStepRepository extends \Doctrine\ORM\EntityRepository
{
}
