<?php

declare(strict_types = 1);

namespace App\Repository;

/**
 * DigitalFormStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigitalFormStepRepository extends \Doctrine\ORM\EntityRepository
{
}
