<?php

declare(strict_types = 1);

namespace App\Repository;

use App\Entity\DigitalFormSchedule;

/**
 * DigitalFormScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigitalFormScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getById(int $id): ?DigitalFormSchedule
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dfs')
            ->from(DigitalFormSchedule::class, 'dfs')
            ->andWhere('dfs.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getByFormId(int $id): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dfs')
            ->from(DigitalFormSchedule::class, 'dfs')
            ->andWhere('dfs.digitalForm = :digitalFormId')
            ->setParameter('digitalFormId', $id)
            ->getQuery()
            ->getResult();
    }

    public function getByFormIds(array $ids): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('dfs')
            ->from(DigitalFormSchedule::class, 'dfs')
            ->andWhere('dfs.digitalForm IN (:digitalForms)')
            ->setParameter('digitalForms', $ids)
            ->getQuery()
            ->getResult();
    }
}
