<?php

namespace App\Repository;

use App\Entity\InspectionForm;
use App\Entity\Team;

/**
 * InspectionFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionFormRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirstInspectionForm(Team $team)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('form')
            ->from(InspectionForm::class, 'form')
            ->leftJoin('form.teams', 't')
            ->where('t = :team')
            ->orWhere('form.isDefault = true')
            ->setParameter('team', $team)
            ->orderBy('t.id')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
