<?php

namespace App\Repository;

/**
 * InspectionFormFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionFormFileRepository extends \Doctrine\ORM\EntityRepository
{
}
