<?php

namespace App\Repository;

/**
 * InspectionFormVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionFormVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
