<?php

namespace App\Repository;

/**
 * InspectionFormDataValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionFormDataValueRepository extends \Doctrine\ORM\EntityRepository
{
}
