<?php

namespace App\Repository;

/**
 * InspectionFormTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionFormTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
