<?php

namespace App\Repository;

/**
 * MobileDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
