<?php

namespace App\Repository;

use App\Entity\Otp;

/**
 * OtpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtpRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $phone
     * @return mixed
     */
    public function invalidateAllForPhone($phone)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete(Otp::class, 'o')
            ->where('o.phone = :phone')
            ->setParameter('phone', $phone)
            ->getQuery()
            ->execute();
    }

    /**
     * @param $userId
     * @return mixed
     */
    public function invalidateAllForUserId($userId)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete(Otp::class, 'o')
            ->where('o.user = :id')
            ->setParameter('id', $userId)
            ->getQuery()
            ->execute();
    }

    /**
     * @param $email
     * @return mixed
     */
    public function invalidateAllForEmail($email)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete(Otp::class, 'o')
            ->where('o.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->execute();
    }

    /**
     * @param $phone
     * @return null|object
     */
    public function findOneByPhone($phone)
    {
        return $this->findOneBy([
            'phone' => $phone,
            'verifiedAt' => null
        ]);
    }

    /**
     * @param $email
     * @return Otp|object
     */
    public function findOneByEmail($email)
    {
        return $this->findOneBy([
            'email' => $email,
            'verifiedAt' => null
        ]);
    }
}
