<?php

namespace App\Repository;

use App\Entity\Permission;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByNameIndexById(array $names)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from(Permission::class, 'p')
            ->andWhere('p.name IN (:names)')
            ->setParameter('names', $names)
            ->indexBy('p', 'p.id')
            ->getQuery()
            ->getResult();
    }

}
