<?php

namespace App\Repository;

use App\Entity\PlatformSetting;

/**
 * PlatformSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformSettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDomain(?string $domain)
    {
        if (!$domain) {
            return null;
        }

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ps')
            ->from(PlatformSetting::class, 'ps')
            ->where('LOWER(ps.domain) = :domain')
            ->setParameter('domain', strtolower($domain))
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
