<?php

namespace App\Repository;

use App\Entity\ReminderCategory;

/**
 * ReminderCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $name
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findUniqueCategory($name)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('rc')
            ->from(ReminderCategory::class, 'rc')
            ->andWhere("LOWER(rc.name) = LOWER(:name)")
            ->andWhere("rc.status = :status")
            ->setParameter('name', $name)
            ->setParameter('status', ReminderCategory::STATUS_ACTIVE);

        return $query->getQuery()->getOneOrNullResult();
    }

    public function updateOrder(int $id, int $order)
    {
        $rcTable = $this->getEntityManager()->getClassMetadata(ReminderCategory::class)->getTableName();

        return $this->getEntityManager()->getConnection()
            ->executeQuery("UPDATE $rcTable SET \"order\" = ? WHERE id = ?", [$order, $id]);
    }
}
