<?php

namespace App\Repository;

use App\Entity\ResetPassword;

/**
 * ResetPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetPasswordRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @return object|null
     */
    public function findOneByUser($user)
    {
        return $this->findOneBy([
            'user' => $user,
            'verifiedAt' => null
        ]);
    }

    /**
     * @param $token
     * @return object|null
     */
    public function findOneByToken($token)
    {
        return $this->findOneBy([
            'token' => $token,
            'verifiedAt' => null
        ]);
    }

    /**
     * @param $user
     * @return mixed
     */
    public function invalidateAllForUser($user)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete(ResetPassword::class, 'rp')
            ->where('rp.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }
}
