<?php

namespace App\Repository;

/**
 * AcknowledgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteFinishAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
