<?php

namespace App\Repository;

/**
 * ScheduledReportRecipientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledReportRecipientsRepository extends \Doctrine\ORM\EntityRepository
{
}
