<?php

namespace App\Repository;

use App\Entity\ScheduledReport;

/**
 * ScheduledReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledReportRepository extends \Doctrine\ORM\EntityRepository
{
}
