<?php

namespace App\Repository;

use App\Entity\Team;
use App\Entity\Theme;
use \Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
    /**
     * @param Team $team
     * @return mixed
     */
    public function findThemesByTeam(Team $team)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->from(Theme::class, 't')
            ->andWhere('t.team = :team')
            ->orWhere('t.team IS NULL')
            ->setParameter('team', $team)
            ->getQuery()
            ->getResult();
    }
}
