<?php

namespace App\Repository;

/**
 * TokenBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenBlacklistRepository extends \Doctrine\ORM\EntityRepository
{
}
