<?php

namespace App\Repository;

use App\Entity\TrackLink;

/**
 * TrackLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackLinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $hash
     * @return int|mixed|string|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByHash($hash)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->from(TrackLink::class, 't')
            ->andWhere('t.hash = :hash')
            ->setParameter('hash', $hash)
            ->andWhere('t.dateFrom < :now')
            ->andWhere('t.dateTo > :dateTo')
            ->setParameter('dateTo', (new \DateTime())->sub(new \DateInterval('PT12H')))
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
