<?php

namespace App\Repository;

use App\Entity\User;
use App\Entity\UserDevice;

/**
 * UserDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDeviceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $email
     * @param $deviceId
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByIdAndTeam($email, $deviceId)
    {
        $user = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from(User::class, 'u')
            ->leftJoin(UserDevice::class, 'd', 'WITH', 'd.user = u')
            ->where('u.email = :email')
            ->andWhere('d.deviceId = :deviceId')
            ->setParameter('email', $email)
            ->setParameter('deviceId', $deviceId)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $user;
    }
}