<?php

namespace App\Repository;

/**
 * VehicleEngineHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleEngineHoursRepository extends \Doctrine\ORM\EntityRepository
{
}
