start:
	docker-compose run -e FORCE_COLOR=1 simulator yarn run start

build:
	docker-compose run -e FORCE_COLOR=1 simulator yarn run build

install:
	docker-compose run simulator yarn install --frozen-lockfile
