<?php

namespace App\Repository\Notification;

use \Doctrine\ORM\EntityRepository;
use App\Entity\Notification\Transport;
use App\Entity\Notification\Event;
use App\Entity\Notification\EventTemplate;
use App\Entity\Notification\Template;
use App\Entity\Notification\TemplateSet;
use Doctrine\ORM\Query\Expr\Join;

/**
 * EventTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTemplateRepository extends EntityRepository
{
    /**
     * @param TemplateSet $set
     * @param Event $event
     * @param array $transports
     * @return Transport[]|array
     */
    public function getEventTemplates(TemplateSet $set, Event $event, array $transports)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from(Template::class, 't')
            ->innerJoin(EventTemplate::class, 'et', Join::WITH, 't.id=et.templateId')
            ->andWhere('et.event = :event')
//            ->andWhere('et.set = :set')
            ->andWhere('t.transport IN (:transports)')
            ->setParameter('event', $event)
//            ->setParameter('set', $set)
            ->setParameter('transports', $transports)
            ->getQuery()
            ->execute()
        ;
    }
}
