<?php

namespace App\Repository\Notification;

use App\Entity\Notification\NotificationMobileDevice;
use Doctrine\Common\Collections\Criteria;

/**
 * NotificationMobileDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationMobileDeviceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @return float|int|mixed|string|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLastLoggedDeviceByUserBy(int $userId)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('nd')
            ->from(NotificationMobileDevice::class, 'nd')
            ->where('nd.user = :user')
            ->andWhere('nd.lastLoggedAt IS NOT NULL')
            ->setParameter('user', $userId)
            ->orderBy('nd.lastLoggedAt', Criteria::DESC)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
