FROM php:8.1.7-fpm as core
# If it crashes with one above then try below:
# FROM php:7.2-fpm-stretch

# PHP
RUN apt-get update && apt-get install -y --no-install-recommends \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        libpq-dev \
        netcat \
        libxml2-dev \
        libc-client-dev \
        libkrb5-dev \
        zlib1g-dev \
        libzip-dev \
        unzip \
        nano \
        git \
    && docker-php-ext-install "-j$(nproc)" iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install "-j$(nproc)" gd \
    && docker-php-ext-install zip \
        bcmath \
        gd \
        mbstring \
        opcache \
        soap \
        pdo pdo_pgsql \
        sockets \
    && rm -r /var/lib/apt/lists/*

RUN pecl install apcu && docker-php-ext-enable apcu
RUN pecl install xdebug-beta && docker-php-ext-enable xdebug

RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
    && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
    && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
    && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --1 \
    && rm -f /tmp/composer-setup.*

WORKDIR /srv

COPY .infra/php-fpm/conf.d/zz-apcu.ini \
  .infra/php-fpm/conf.d/zz-memory-limit.ini \
  .infra/php-fpm/conf.d/zz-xdebug.ini \
   /usr/local/etc/php/conf.d/

COPY .infra/php-fpm/php-fpm.d/www.dev.conf /usr/local/etc/php-fpm.d/www.conf

COPY .infra/php-fpm/boot.sh /usr/local/bin/boot.sh
CMD ["bash", "/usr/local/bin/boot.sh"]
