<?php

namespace App\Repository\Tracker\Teltonika;

/**
 * TrackerSimulatorTrackPayloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerSimulatorTrackPayloadRepository extends \Doctrine\ORM\EntityRepository
{
}
