<?php

namespace App\Repository\Tracker\Teltonika;

/**
 * TrackerSimulatorTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerSimulatorTrackRepository extends \Doctrine\ORM\EntityRepository
{
}
