<?php

namespace App\Repository\Tracker\Teltonika;

use App\Entity\Device;
use App\Entity\Tracker\Teltonika\TrackerSensorEvent;
use \Doctrine\ORM\EntityRepository;

/**
 * TrackerSensorEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackerSensorEventRepository extends EntityRepository
{
    /**
     * @param array $eventRemoteIds
     * @param Device $device
     * @return mixed
     */
    public function getTrackerSensorEventData(array $eventRemoteIds, Device $device)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ts.id, ts.remoteId')
            ->from(TrackerSensorEvent::class, 'ts')
            ->andWhere('ts.deviceModel = :deviceModel')
            ->andWhere('ts.remoteId in (:eventRemoteIds)')
            ->setParameter('deviceModel', $device->getModel())
            ->setParameter('eventRemoteIds', $eventRemoteIds);

        return $query->getQuery()->getResult();
    }
}
