<?php

namespace App\Repository\Notification\Alert;

use App\Entity\Notification\Alert\AlertSetting;

/**
 * AlertSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertSettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeClientAlertSettingById(array $ids)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete(AlertSetting::class, 'a')
            ->andWhere('a.id NOT IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()->execute();
    }
}
