<?php

namespace App\Repository\Notification\Alert;

/**
 * AlertSubTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertSubTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
