<?php

namespace App\Repository\FuelCard;

/**
 * FuelCardTemporaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelCardTemporaryRepository extends \Doctrine\ORM\EntityRepository
{
}
