<?php

namespace App\Repository\FuelType;

/**
 * FuelMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
