<?php

namespace App\Repository\FuelType;

use App\Entity\BaseEntity;
use App\Entity\FuelType\FuelMapping;
use App\Entity\FuelType\FuelType;

/**
 * FuelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $refueledFuelType
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFuelTypeMapping($refueledFuelType)
    {
        $fuelType = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ft')
            ->from(FuelType::class, 'ft')
            ->leftJoin(FuelMapping::class, 'fm', 'WITH', 'ft.id = fm.fuelType')
            ->where('LOWER(ft.name) = :fuelType')
            ->orWhere('LOWER(fm.name) = :fuelType')
            ->andWhere('fm.status = :status')
            ->setParameter('fuelType', strtolower($refueledFuelType))
            ->setParameter('status', BaseEntity::STATUS_ACTIVE)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();

        return $fuelType;
    }
}
